name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # <-- Add this at the top level

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (using version 18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies using your lock file
      - name: Install dependencies
        run: npm ci

      # Step 4: Build your project (runs the build script defined in package.json)
      - name: Build the project
        run: npm run build

      # Step 5: Ensure remote 'origin' exists
      - name: Ensure remote origin exists
        run: |
          if git remote | grep -q "^origin$"; then
            git remote rm origin
          fi
          git remote add origin https://github.com/${{ github.repository }}.git

      # Step 6: Deploy the built files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
